apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/where-for-dinner-ui
  creationTimestamp: null
  name: where-for-dinner-ui.apps.local.20241008.1105.54659
spec:
  refName: where-for-dinner-ui.apps.local
  releasedAt: "2024-10-08T11:15:37Z"
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait=false
      fetch:
      - imgpkgBundle:
          image: quay.io/tpapps/wfd/where-for-dinner-ui@sha256:a61c8d8c9c83cb6c324550301932ad25210617cdef712ac63e8e991e615ed478
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
  valuesSchema:
    openAPIv3: null
  version: 20241008.1105.54659
