apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/where-for-dinner-search-proc
  creationTimestamp: null
  name: where-for-dinner-search-proc.apps.local.20241008.1105.54659
spec:
  refName: where-for-dinner-search-proc.apps.local
  releasedAt: "2024-10-08T11:12:40Z"
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait=false
      fetch:
      - imgpkgBundle:
          image: quay.io/tpapps/wfd/where-for-dinner-search-proc@sha256:8e2f966f4215a907adb2b019f08ebad54c493ba52781eaf6ce5e72877770e4b3
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
  valuesSchema:
    openAPIv3: null
  version: 20241008.1105.54659
