apiVersion: apps.tanzu.vmware.com/v1
kind: ContainerApp
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/where-for-dinner-ui
    containerapp.apps.tanzu.vmware.com/class: kubernetes
  name: where-for-dinner-ui
spec:
  content:
    buildTimestamp: "2024-10-08T11:05:54Z"
    gitCommit: 8fb6112c42d26b1ad11840040c8337109364d000-dirty
    gitURL: github.com/vmware-tanzu/application-accelerator-samples.git
    packageImage: quay.io/tpapps/wfd/where-for-dinner-ui@sha256:a61c8d8c9c83cb6c324550301932ad25210617cdef712ac63e8e991e615ed478
    packageRefName: where-for-dinner-ui.apps.local
    packageVersion: 20241008.1105.54659
    summary: git:8fb6112 @ 2024-10-08T11:05:54Z
    version: 20241008.1105.54659
  health:
    maxUnavailableReplicas: 10%
  image: quay.io/tpapps/wfd/where-for-dinner-ui:20241008.1105.54659@sha256:861af648af057c381b2b2c10a7bbe60295e5cd6d912d712752efb61b31a05a61
  ports:
  - name: main
    port: 8080
  relatedRefs:
  - for: kubernetes.list-replicas
    kind: Pod
    labelSelector: containerapp.apps.tanzu.vmware.com/app-name=where-for-dinner-ui
  - apiGroup: apps
    for: kubernetes.service-binding-target
    kind: Deployment
    name: where-for-dinner-ui
  - for: kubernetes.service-target
    kind: Service
    name: where-for-dinner-ui
  - for: kubernetes.scale-replicas
    keyPath: .data['values.yml']->[yaml].replicas
    kind: Secret
    name: where-for-dinner-ui-values
  - for: kubernetes.scale-resources
    keyPath: .data['values.yml']->[yaml].resources
    kind: Secret
    name: where-for-dinner-ui-values
  - for: kubernetes.set-secret-env
    keyPath: .data['values.yml']->[yaml].secretEnv
    kind: Secret
    name: where-for-dinner-ui-values
  - apiGroup: packaging.carvel.dev
    for: kubernetes.delete
    kind: PackageInstall
    name: where-for-dinner-ui
  - apiGroup: data.packaging.carvel.dev
    for: kubernetes.delete
    kind: Package
    name: where-for-dinner-ui.apps.local.20241008.1105.54659
  - for: kubernetes.delete
    kind: Secret
    name: where-for-dinner-ui-values
  - for: kubernetes.set-content-hash
    keyPath: .data['values.yml']->[yaml].contentHash
    kind: Secret
    name: where-for-dinner-ui-values
  - for: kubernetes.set-content-version
    keyPath: .data['values.yml']->[yaml].contentVersion
    kind: Secret
    name: where-for-dinner-ui-values
  resources:
    cpu: 300m
    memory: 1Gi
