apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/where-for-dinner-availability
  creationTimestamp: null
  name: where-for-dinner-availability.apps.local.20241008.1105.54659
spec:
  refName: where-for-dinner-availability.apps.local
  releasedAt: "2024-10-08T11:07:44Z"
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait=false
      fetch:
      - imgpkgBundle:
          image: quay.io/tpapps/wfd/where-for-dinner-availability@sha256:fd6b73a27a5ae4df642da7ceff2c5f086c092062661ce44f3ac024ede5e9c8e3
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
  valuesSchema:
    openAPIv3: null
  version: 20241008.1105.54659
