apiVersion: apps.tanzu.vmware.com/v1
kind: ContainerApp
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/where-for-dinner-search-proc
    containerapp.apps.tanzu.vmware.com/class: kubernetes
  name: where-for-dinner-search-proc
spec:
  acceptedServiceBindings:
  - name: rmq
    types:
    - rabbitmq
  content:
    buildTimestamp: "2024-10-08T11:05:54Z"
    gitCommit: 8fb6112c42d26b1ad11840040c8337109364d000-dirty
    gitURL: github.com/vmware-tanzu/application-accelerator-samples.git
    packageImage: quay.io/tpapps/wfd/where-for-dinner-search-proc@sha256:8e2f966f4215a907adb2b019f08ebad54c493ba52781eaf6ce5e72877770e4b3
    packageRefName: where-for-dinner-search-proc.apps.local
    packageVersion: 20241008.1105.54659
    summary: git:8fb6112 @ 2024-10-08T11:05:54Z
    version: 20241008.1105.54659
  health:
    maxUnavailableReplicas: 10%
  image: quay.io/tpapps/wfd/where-for-dinner-search-proc:20241008.1105.54659@sha256:008684f2cce312d195acf69a6707862bcc90437db5f509e7ed88abe8df98405f
  nonSecretEnv:
  - name: spring_profiles_active
    value: crawler
  - name: JAVA_TOOL_OPTIONS
    value: -Dmanagement.endpoint.health.probes.add-additional-paths=true -Dmanagement.health.probes.enabled=true
      -Dserver.port=8080
  ports:
  - name: main
    port: 8080
  probes:
    liveness:
      httpGet:
        path: /livez
        port: 8080
        scheme: HTTP
    readiness:
      httpGet:
        path: /readyz
        port: 8080
        scheme: HTTP
    startup:
      failureThreshold: 120
      httpGet:
        path: /readyz
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 1
      periodSeconds: 1
  relatedRefs:
  - for: kubernetes.list-replicas
    kind: Pod
    labelSelector: containerapp.apps.tanzu.vmware.com/app-name=where-for-dinner-search-proc
  - apiGroup: apps
    for: kubernetes.service-binding-target
    kind: Deployment
    name: where-for-dinner-search-proc
  - for: kubernetes.service-target
    kind: Service
    name: where-for-dinner-search-proc
  - for: kubernetes.scale-replicas
    keyPath: .data['values.yml']->[yaml].replicas
    kind: Secret
    name: where-for-dinner-search-proc-values
  - for: kubernetes.scale-resources
    keyPath: .data['values.yml']->[yaml].resources
    kind: Secret
    name: where-for-dinner-search-proc-values
  - for: kubernetes.set-secret-env
    keyPath: .data['values.yml']->[yaml].secretEnv
    kind: Secret
    name: where-for-dinner-search-proc-values
  - apiGroup: packaging.carvel.dev
    for: kubernetes.delete
    kind: PackageInstall
    name: where-for-dinner-search-proc
  - apiGroup: data.packaging.carvel.dev
    for: kubernetes.delete
    kind: Package
    name: where-for-dinner-search-proc.apps.local.20241008.1105.54659
  - for: kubernetes.delete
    kind: Secret
    name: where-for-dinner-search-proc-values
  - for: kubernetes.set-content-hash
    keyPath: .data['values.yml']->[yaml].contentHash
    kind: Secret
    name: where-for-dinner-search-proc-values
  - for: kubernetes.set-content-version
    keyPath: .data['values.yml']->[yaml].contentVersion
    kind: Secret
    name: where-for-dinner-search-proc-values
  resources:
    cpu: 300m
    memory: 1Gi
